const test=require('node:test'),assert=require('node:assert/strict'),G=require('./public/graph-math');
test('Zoom preserves the world point under the pointer without changing node positions',()=>{const camera={x:90,y:45,scale:.8},p={x:220,y:130},node={x:30,y:50};const before=G.world(p,camera),next=G.zoom(camera,1.3,p),after=G.world(p,next);assert(Math.abs(before.x-after.x)<1e-9);assert(Math.abs(before.y-after.y)<1e-9);assert.deepEqual(node,{x:30,y:50});});
test('Camera transforms round-trip and panning changes no world coordinates',()=>{const n={x:-300,y:220},c={x:120,y:-35,scale:2};assert.deepEqual(G.world(G.screen(n,c),c),n);assert.deepEqual(G.world(G.screen(n,{...c,x:c.x+75}),{...c,x:c.x+75}),n);});
test('Filters combine strictly and accent-insensitive search covers titles, tags and folders',()=>{const n={id:'a',type:'atomica',label:'Generación',tags:['memory'],carpeta:'Learning'};assert(G.matches(n,'generacion','memory','atomica'));assert(!G.matches(n,'generacion','memory','mapa'));assert(G.matches(n,'learning','',''));assert(!G.matches(n,'missing','',''));});
test('Filtered out nodes cannot be hit',()=>{const nodes=[{id:'a',x:0,y:0,r:12,type:'atomica'},{id:'b',x:50,y:50,r:12,type:'fuente'}],c={x:0,y:0,scale:1};const visible=nodes.filter(n=>G.matches(n,'','','fuente'));assert.equal(G.hit(visible,{x:0,y:0},c),null);assert.equal(G.hit(visible,{x:50,y:50},c).id,'b');});
test('Fit handles empty and single graphs and includes all nodes',()=>{assert(Number.isFinite(G.fit([],390,420).scale));const nodes=[{x:-300,y:-200,r:20},{x:400,y:300,r:15}];const c=G.fit(nodes,390,420);for(const n of nodes){const p=G.screen(n,c);assert(p.x>=0&&p.x<=390&&p.y>=0&&p.y<=420);}assert(Number.isFinite(G.fit([nodes[0]],390,420).scale));});
test('Simulation separates coincident nodes and stays finite',()=>{const nodes=[{id:'a',x:0,y:0,r:12,vx:0,vy:0},{id:'b',x:0,y:0,r:12,vx:0,vy:0}];const map=new Map(nodes.map(n=>[n.id,n]));for(let i=0;i<150;i++)G.step(nodes,[{source:'a',target:'b'}],map);assert(Math.hypot(nodes[0].x-nodes[1].x,nodes[0].y-nodes[1].y)>40);for(const n of nodes)assert(Number.isFinite(n.x)&&Number.isFinite(n.y));});
test('Label collision detection rejects overlaps, permits disjoint boxes',()=>{assert(G.overlaps({x:0,y:0,w:20,h:20},{x:10,y:10,w:20,h:20}));assert(!G.overlaps({x:0,y:0,w:20,h:20},{x:30,y:30,w:10,h:10}));});
test('Graph loading failure exposes retry instead of a silent blank canvas',async()=>{
 const fs=require('fs'),vm=require('vm');
 const elements=new Map();
 const el=()=>({textContent:'',hidden:false,style:{},classList:{toggle(){}},setAttribute(){},replaceChildren(){},append(){},getContext(){return null;},parentElement:{clientWidth:800,clientHeight:500}});
 const ctx={GraphMath:G,state:{currentView:'grafo',graphSearchQuery:'',selectedGraphTag:'',selectedGraphType:null,isGraphPhysicsActive:false},window:{devicePixelRatio:2},document:{getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id);},createElement:el},t:key=>key,fetch:async()=>{throw Error('offline');},cancelAnimationFrame(){}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('public/graph.js','utf8'),ctx);
 await ctx.renderGraph();assert.equal(elements.get('graph-status').textContent,'graphError');assert.equal(elements.get('graph-retry').hidden,false);
 ctx.fetch=async()=>({ok:true,json:async()=>({nodes:[],links:[]})});await ctx.renderGraph();assert.equal(elements.get('graph-retry').hidden,true);assert.equal(elements.get('graph-empty').textContent,'graphNoNotes');assert.equal(elements.get('graph-empty').hidden,false);
});
